"""Module for executing and validating generated solutions."""

import importlib.util
import logging
import re
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

from shared.errors import (
    ExecutionError,
    TimeoutError,
    CompilationError,
    RuntimeError,
    ResourceError,
)
from shared.performance import PerformanceMonitor, PerformanceMetrics
from shared.quality.code_formatter import format_code
from shared.tempfiles import TempFileManager
from shared.config import RESOURCES_CONFIG, DEFAULT_EXECUTION_TIMEOUT
import asyncio

logger = logging.getLogger(__name__)


@dataclass
class TestCase:
    """Test case for validating a solution."""

    input_data: str
    expected_output: str
    description: Optional[str] = None

    def to_dict(self) -> Dict[str, Any]:
        """Convert the TestCase instance to a dictionary for JSON serialization."""
        return {
            "input_data": self.input_data,
            "expected_output": self.expected_output,
            "description": self.description,
        }


@dataclass
class ExecutionResult:
    """Result of executing a solution."""

    output: str
    performance: Optional[PerformanceMetrics] = None
    error: Optional[str] = None


class SolutionExecutor:
    """Handles execution and validation of generated solutions."""

    def __init__(self, workspace_dir: Path) -> None:
        """Initialize the solution executor.
        
        Args:
            workspace_dir: Workspace directory path
        """
        self.workspace_dir = workspace_dir
        self.temp_manager = TempFileManager(workspace_dir)
        self.performance_monitor = PerformanceMonitor()

    async def prepare_solution(
        self, problem_id: str, source_code: str, test_cases: List[TestCase], model_name: str = ""
    ) -> Tuple[bool, Optional[str]]:
        """Prepare and validate a solution.

        Args:
            problem_id: Unique identifier for the problem (e.g., "2021_day1_part1")
            source_code: Generated solution code
            test_cases: List of test cases to validate against
            model_name: Name of the model generating this solution

        Returns:
            Tuple of (is_valid, error_message)
        """
        # Create a temporary module for this solution
        model_suffix = f"_{model_name.replace(':', '_')}" if model_name else ""
        module_path = self.temp_manager.create_temp_file(f"{problem_id}{model_suffix}.py")

        try:
            # Format the code before validation
            formatted_code, _ = format_code(source_code)

            # Add model attribution comment
            if model_name:
                formatted_code = f"# Generated by model: {model_name}\n{formatted_code}"

            # Log the formatted code for debugging
            logger.debug("Generated solution code:\n%s", formatted_code)

            # Write the solution to a temporary file
            module_path.write_text(formatted_code)

            # Try to import it to check for syntax errors
            spec = importlib.util.spec_from_file_location(
                f"solution_{problem_id}", module_path
            )
            if not spec or not spec.loader:
                raise CompilationError("Failed to create module specification")

            module = importlib.util.module_from_spec(spec)
            sys.modules[spec.name] = module
            spec.loader.exec_module(module)

            # Verify it has a solve function
            if not hasattr(module, "solve"):
                raise CompilationError("Solution must contain a solve() function")

            # Run test cases
            for test_case in test_cases:
                # Create test input file in the same directory as the real input
                year, day, part = re.match(r"(\d+)_day(\d+)_part(\d)", problem_id).groups()
                input_dir = self.workspace_dir / "years" / year / f"day{int(day):02d}"
                input_file = input_dir / "input.txt"

                # Temporarily write test input
                orig_content = None
                if input_file.exists():
                    orig_content = input_file.read_text()
                input_file.write_text(test_case.input_data)

                try:
                    # Set input file path and execute
                    result = await self.execute_solution(module_path, str(input_file))

                    if (
                        result.error
                        or result.output.strip() != test_case.expected_output.strip()
                    ):
                        raise ExecutionError(
                            f"Test case failed: {result.error or 'Output mismatch'}"
                        )

                except (IOError, OSError) as e:
                    logger.error("IO error during test case execution: %s", str(e))
                    raise ExecutionError(str(e)) from e

                finally:
                    # Restore original content
                    if orig_content is not None:
                        input_file.write_text(orig_content)
                    else:
                        input_file.unlink()

            return True, None

        except (SyntaxError, IndentationError) as e:
            raise CompilationError(f"Invalid Python syntax: {str(e)}") from e
        except IOError as e:
            raise ExecutionError(f"Failed to write solution file: {str(e)}") from e
        except Exception as e:
            logger.error("Unexpected error preparing solution: %s", str(e))
            raise ExecutionError(str(e)) from e

    async def execute_solution(
        self, module_path: Path, input_path: str
    ) -> ExecutionResult:
        """Execute a solution module with input data.
        
        Args:
            module_path: Path to solution module
            input_path: Path to input data file
            
        Returns:
            ExecutionResult containing output and performance metrics
        """
        try:
            # Get resource limits from config
            timeout = RESOURCES_CONFIG.get("execution", {}).get("timeout_seconds", DEFAULT_EXECUTION_TIMEOUT)
            max_memory = RESOURCES_CONFIG.get("execution", {}).get("max_memory_mb", 512)
            max_processes = RESOURCES_CONFIG.get("execution", {}).get("max_processes", 1)
            
            # Create subprocess with resource limits
            process = await asyncio.create_subprocess_exec(
                sys.executable,
                str(module_path),
                input_path,
                stdout=asyncio.subprocess.PIPE,
                stderr=asyncio.subprocess.PIPE,
                limit=max_memory * 1024 * 1024,  # Convert MB to bytes
            )
            
            try:
                stdout, stderr = await asyncio.wait_for(
                    process.communicate(), timeout=timeout
                )
                
                if process.returncode != 0:
                    error_msg = stderr.decode() if stderr else "Unknown error"
                    return ExecutionResult("", error=f"Process failed: {error_msg}")
                    
                return ExecutionResult(stdout.decode())
                
            except asyncio.TimeoutError:
                process.terminate()
                return ExecutionResult(
                    "", error=f"Solution timed out after {timeout} seconds"
                )
                
        except Exception as e:
            return ExecutionResult("", error=str(e))

    async def run_against_full_input(
        self, problem_id: str, year: int, day: int, part: int, source_code: str
    ) -> ExecutionResult:
        """Run a solution against the full input data.

        Args:
            problem_id: Unique identifier for the problem
            year: Problem year
            day: Problem day
            part: Problem part
            source_code: Solution source code

        Returns:
            ExecutionResult from running against full input
        """
        input_file = (
            self.workspace_dir / "years" / str(year) / f"day{day:02d}" / "input.txt"
        )

        if not input_file.exists():
            return ExecutionResult(
                output="", performance=None, error=f"Input file not found: {input_file}"
            )

        # Create solution module
        module_path = self.temp_manager.create_temp_file(f"{problem_id}.py")
        module_path.write_text(source_code)

        # Execute the solution
        result = await self.execute_solution(module_path, str(input_file))

        return result

    async def test_solution(
        self,
        solution_code: str,
        year: int,
        day: int,
        part: int,
        test_cases: Optional[List[TestCase]] = None,
        model_name: str = "",
        debug: bool = False
    ) -> Tuple[List[ExecutionResult], Optional[ExecutionResult], Optional[str]]:
        """Test a solution against example cases and full input.

        Args:
            solution_code: The solution code to test
            year: Problem year
            day: Problem day
            part: Problem part
            test_cases: Optional list of test cases. If None, uses default test cases.
            model_name: Name of the model that generated this solution
            debug: Whether to enable debug output

        Returns:
            Tuple containing:
            - List[ExecutionResult]: Results from example tests
            - Optional[ExecutionResult]: Result from full input test (None if examples failed)
            - Optional[str]: Full input answer if successful, None otherwise
        """
        try:
            problem_id = f"{year}_day{day:02d}_part{part}"
            example_results = []
            full_result = None
            full_answer = None

            # Validate the solution code
            is_valid, error = await self.prepare_solution(
                problem_id, solution_code, test_cases or [], model_name=model_name
            )
            if not is_valid:
                return [], None, None

            # Run example tests
            for i, test_case in enumerate(test_cases or [], 1):
                try:
                    result = await self._run_test_case(
                        problem_id, solution_code, test_case, year, day, i
                    )
                    example_results.append(result)
                except Exception as e:
                    example_results.append(
                        ExecutionResult(output="", error=f"Test case {i} error: {str(e)}")
                    )

            # Run against full input if examples pass
            if all(result.error is None for result in example_results):
                try:
                    full_result = await self.run_against_full_input(
                        problem_id, year, day, part, solution_code
                    )
                    if full_result.error is None:
                        full_answer = full_result.output.strip()
                except Exception as e:
                    full_result = ExecutionResult(
                        output="", error=f"Error running against full input: {str(e)}"
                    )

            return example_results, full_result, full_answer

        except Exception as e:
            logger.error("Unexpected error testing solution: %s", str(e))
            return [], None, None

    async def _run_test_case(
        self, problem_id: str, solution_code: str, test_case: TestCase, year: int, day: int, test_case_index: int
    ) -> ExecutionResult:
        # Create solution module
        module_path = self.temp_manager.create_temp_file(f"{problem_id}.py")
        module_path.write_text(solution_code)

        # Create test input file
        input_file = self._create_test_input(test_case.input_data)

        # Execute the solution
        result = await self.execute_solution(module_path, str(input_file))

        return result

    def _create_test_input(self, input_data: str) -> str:
        # Create a temporary file for input data
        input_path = self.temp_manager.create_temp_file("input.txt")
        input_path.write_text(input_data)
        return str(input_path)

    def cleanup(self) -> None:
        """Clean up temporary files."""
        self.temp_manager.cleanup()

    def extract_test_cases(self, problem_text: str) -> List[Dict[str, Any]]:
        """Extract test cases from problem text."""
        test_cases = []
        current_example = None

        # Split into sections by double newlines
        sections = problem_text.split("\n\n")
        for section in sections:
            # Look for example header
            if "Example" in section or "example" in section:
                # Look for number block
                number_block = re.search(r"(?m)^(\d+\n)+\d+$", section)
                if number_block:
                    current_example = {
                        "description": section,
                        "input": number_block.group(0),
                    }
                    continue

            # Look for output
            if current_example:
                output_match = re.search(
                    r"(?m)(?:answer|output|result).*?[is:]?\s*[*]?(\d+)[*]?",
                    section,
                    re.IGNORECASE,
                )
                if output_match:
                    test_case = TestCase(
                        description=current_example["description"],
                        input_data=current_example["input"],
                        expected_output=output_match.group(1),
                    )
                    test_cases.append(test_case.to_dict())
                    current_example = None

        return test_cases
